// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JtTcc.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JtTcc.Models.Pagina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sg_Nome");

                    b.HasKey("Id");

                    b.ToTable("tb_pagina", (string)null);
                });

            modelBuilder.Entity("JtTcc.Models.PermissaoPaginas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PaginaId")
                        .HasColumnType("int")
                        .HasColumnName("cd_Pagina_Permissao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("cd_Usuario");

                    b.HasKey("Id");

                    b.ToTable("tb_permissao_pagina", (string)null);
                });

            modelBuilder.Entity("JtTcc.Models.PortaoLocalizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nm_portao_localizacao");

                    b.HasKey("Id");

                    b.ToTable("tb_portao_localizacao", (string)null);
                });

            modelBuilder.Entity("JtTcc.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ic_ativo");

                    b.Property<string>("Base64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("base64");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cd_cpf");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cd_celular");

                    b.Property<DateTime>("Create")
                        .HasColumnType("datetime2")
                        .HasColumnName("is_create");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_observacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nm_nome");

                    b.Property<bool>("Pedestre")
                        .HasColumnType("bit")
                        .HasColumnName("ic_pedestre");

                    b.Property<int>("PortaoId")
                        .HasColumnType("int")
                        .HasColumnName("pk_PortaId");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cd_tag");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("pk_usuarioId");

                    b.Property<bool>("Visitante")
                        .HasColumnType("bit")
                        .HasColumnName("ic_visitante");

                    b.HasKey("Id");

                    b.ToTable("tb_registro", (string)null);
                });

            modelBuilder.Entity("JtTcc.Models.TipoEntrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Create")
                        .HasColumnType("datetime2")
                        .HasColumnName("cd_create");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int")
                        .HasColumnName("pk_registroId");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("cd_tipo_entrada");

                    b.HasKey("Id");

                    b.ToTable("tb_tipoEntrada", (string)null);
                });

            modelBuilder.Entity("JtTcc.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("active");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cd_cpf");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cd_celular");

                    b.Property<DateTime>("Create")
                        .HasColumnType("datetime2")
                        .HasColumnName("create");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cd_login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cd_nome");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int")
                        .HasColumnName("pk_registroId");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cd_senha");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("cd_status");

                    b.HasKey("Id");

                    b.ToTable("tb_usuario", (string)null);
                });

            modelBuilder.Entity("JtTcc.Models.UsuarioFuncao", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("cd_usuario");

                    b.Property<int>("FuncaoId")
                        .HasColumnType("int")
                        .HasColumnName("cd_funcao");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ic_ativo");

                    b.Property<DateTime>("DataAssociacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_associacao");

                    b.HasKey("UsuarioId", "FuncaoId");

                    b.ToTable("tb_usuario_funcao", (string)null);
                });

            modelBuilder.Entity("JtTcc.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cd_placa");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int")
                        .HasColumnName("pk_registroId");

                    b.Property<string>("TipoVeiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cd_tipo_veiculo");

                    b.HasKey("Id");

                    b.ToTable("tb_veiculo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
